"""
Testing
"""
import logging
import sys

from antlr4 import *

from language.parser.autogenerated.NeuralLogLexer import NeuralLogLexer
from language.parser.autogenerated.NeuralLogParser import NeuralLogParser
from language.parser.neural_log_listener import NeuralLogTransverse


def configure_log():
    """
    Configures the log handler, message format and log level
    """
    handlers = [
        logging.StreamHandler(sys.stdout),
    ]
    logging.basicConfig(
        format='%(message)s',
        level=logging.INFO,
        handlers=handlers
    )


def main(argv):
    """
    Main function.

    :param argv: the arguments
    :type argv: list[str]
    """
    lexer = NeuralLogLexer(FileStream(argv[1]))
    stream = CommonTokenStream(lexer)
    parser = NeuralLogParser(stream)
    tree = parser.program()

    transverse = NeuralLogTransverse()
    transverse(tree)

    for clause in transverse.clauses:
        print(clause)
    print("\nPredicates: ({})".format(len(transverse.predicates)))
    for predicate in sorted(transverse.predicates, key=lambda x: x.key()):
        print(predicate)

    print("\nConstants: ({})".format(len(transverse.constants)))
    for constant in sorted(transverse.constants, key=lambda x: x.key()):
        print(constant)


if __name__ == "__main__":
    configure_log()
    main(sys.argv)
