1.0::example(grand_father, andrew, charlotte).
1.0::example(grand_father, andrew, colin).
1.0::example(grand_father, pierro, arthur).
1.0::example(grand_father, pierro, victoria).
1.0::example(grand_father, pierro, emilio).
1.0::example(grand_father, pierro, alfonso).
1.0::example(grand_father, pierro, sophia).
1.0::example(grand_mother, maria, sophia).
1.0::example(grand_mother, maria, angela).
1.0::example(grand_mother, maria, marco).
