1.0::example(similarity, andrew, andrew, andrew).
1.0::example(similarity, andrew, christopher, christopher).
1.0::example(similarity, andrew, james, james).
1.0::example(similarity, christopher, andrew, andrew).
1.0::example(similarity, christopher, christopher, christopher).
1.0::example(similarity, christopher, james, james).
1.0::example(similarity, james, andrew, andrew).
1.0::example(similarity, james, christopher, christopher).
1.0::example(similarity, james, james, james).
