"""
Testing
"""
import logging
import sys

from antlr4 import *

from program.language import NeuralLogProgram, Predicate
from program.parser.autogenerated.NeuralLogLexer import NeuralLogLexer
from program.parser.autogenerated.NeuralLogParser import NeuralLogParser
from program.parser.neural_log_listener import NeuralLogTransverse


def configure_log():
    """
    Configures the log handler, message format and log level
    """
    h1 = logging.StreamHandler(sys.stdout)
    h1.setLevel(logging.INFO)
    h1.addFilter(lambda record: record.levelno <= logging.INFO)
    h2 = logging.StreamHandler(sys.stderr)
    h2.setLevel(logging.WARNING)
    handlers = [h1, h2]
    logging.basicConfig(
        format='%(message)s',
        level=logging.INFO,
        handlers=handlers
    )


def main(argv):
    """
    Main function.

    :param argv: the arguments
    :type argv: list[str]
    """
    lexer = NeuralLogLexer(FileStream(argv[1]))
    stream = CommonTokenStream(lexer)
    parser = NeuralLogParser(stream)
    tree = parser.program()

    transverse = NeuralLogTransverse()
    transverse(tree)

    for clause in transverse.clauses:
        print(clause)
    print("\nPredicates: ({})".format(len(transverse.predicates)))
    for predicate in sorted(transverse.predicates, key=lambda x: x.key()):
        print(predicate)

    print("\nConstants: ({})".format(len(transverse.constants)))
    for constant in sorted(transverse.constants, key=lambda x: x.key()):
        print(constant)

    print("\n\nNeuralLog Program:\n")
    neural_program = NeuralLogProgram(transverse.clauses)

    print("Facts: ({})".format(
        sum(map(lambda x: len(x), neural_program.facts_by_predicate.values()))
    ))
    for predicate in sorted(neural_program.facts_by_predicate.keys(),
                            key=lambda x: x.__str__()):
        for fact in neural_program.facts_by_predicate[predicate].values():
            print(fact)

    print("\n\nClauses: ({})".format(len(neural_program.clauses)))
    for clause in neural_program.clauses:
        print(clause)

    print("\n\nPredicates: ({})".format(len(neural_program.predicates)))
    for predicate in sorted(neural_program.predicates.keys(),
                            key=lambda x: x.__str__()):
        if predicate in neural_program.logic_predicates:
            print("LOGIC   ", predicate, sep="\t")
        else:
            print("FUNCTION", predicate, sep="\t")

    print("\n\nIterable Constants: ({})"
          .format(len(neural_program.iterable_constants)))
    iterable_constants = set()
    for k, v in neural_program.iterable_constants.items():
        iterable_constants.add(v)
        print("{}:\t{}".format(k, v))

    other_constants = neural_program.constants - iterable_constants
    print("\n\nOther Constants: ({})"
          .format(len(other_constants)))
    for constant in other_constants:
        print(constant)

    father_matrix = neural_program.get_matrix_representation(Predicate(
        "father", 2))
    mother_matrix = neural_program.get_matrix_representation(Predicate(
        "mother", 2))

    print("\nFather Matrix:")
    print(father_matrix)
    print("\nMother Matrix:")
    print(mother_matrix)

    grand_father = father_matrix.dot(father_matrix) + \
                   father_matrix.dot(mother_matrix)

    # grand_father = neural_program.get_matrix_representation(Predicate(
    #     "grand_father", 2))

    # print("\nGrandfather Matrix:")
    # print(grand_father)

    print()
    for i, j in zip(*grand_father.nonzero()):
        print("{}::{}({}, {}).".format(grand_father[i, j],
                                       "grand_father",
                                       neural_program.iterable_constants[i],
                                       neural_program.iterable_constants[j]))

    print("\n")
    test = Predicate("test")
    print("{}::{}.".format(neural_program.get_matrix_representation(test)[0],
                           test.name))

    print("\n")
    male = Predicate("male", 1)
    print(male)
    representation = neural_program.get_matrix_representation(male)
    for i, j in zip(*representation.nonzero()):
        print("{}::{}({}).".format(
            representation[i, j],
            "male",
            neural_program.iterable_constants[i]
        ))

    print("\n")
    age = Predicate("age", 2)
    print(age)
    age_weights, age_attributes = neural_program.get_matrix_representation(age)
    for i, j in zip(*age_weights.nonzero()):
        print("{}::{}({}, {}).".format(
            age_weights[i, j],
            "age",
            neural_program.iterable_constants[i],
            age_attributes[i, j],
        ))


if __name__ == "__main__":
    configure_log()
    main(sys.argv)
