mega_example(0, ner, "22", "B").
mega_example(0, ner, "-", "I").
mega_example(0, ner, "oxacalcitriol", "I").
mega_example(0, ner, "suppresses", "O").
mega_example(0, ner, "secondary", "O").
mega_example(0, ner, "hyperparathyroidism", "O").
mega_example(0, ner, "without", "O").
mega_example(0, ner, "inducing", "O").
mega_example(0, ner, "low", "O").
mega_example(0, ner, "bone", "O").
mega_example(0, ner, "turnover", "O").
mega_example(0, ner, "in", "O").
mega_example(0, ner, "dogs", "O").
mega_example(0, ner, "with", "O").
mega_example(0, ner, "renal", "O").
mega_example(0, ner, "failure", "O").
mega_example(0, ner, ".", "O").

mega_example(1, ner, "BACKGROUND", "O").
mega_example(1, ner, ":", "O").
mega_example(1, ner, "Calcitriol", "B").
mega_example(1, ner, "therapy", "O").
mega_example(1, ner, "suppresses", "O").
mega_example(1, ner, "serum", "O").
mega_example(1, ner, "levels", "O").
mega_example(1, ner, "of", "O").
mega_example(1, ner, "parathyroid", "O").
mega_example(1, ner, "hormone", "O").
mega_example(1, ner, "(", "O").
mega_example(1, ner, "PTH", "O").
mega_example(1, ner, ")", "O").
mega_example(1, ner, "in", "O").
mega_example(1, ner, "patients", "O").
mega_example(1, ner, "with", "O").
mega_example(1, ner, "renal", "O").
mega_example(1, ner, "failure", "O").
mega_example(1, ner, "but", "O").
mega_example(1, ner, "has", "O").
mega_example(1, ner, "several", "O").
mega_example(1, ner, "drawbacks", "O").
mega_example(1, ner, ",", "O").
mega_example(1, ner, "including", "O").
mega_example(1, ner, "hypercalcemia", "O").
mega_example(1, ner, "and", "O").
mega_example(1, ner, "/", "O").
mega_example(1, ner, "or", "O").
mega_example(1, ner, "marked", "O").
mega_example(1, ner, "suppression", "O").
mega_example(1, ner, "of", "O").
mega_example(1, ner, "bone", "O").
mega_example(1, ner, "turnover", "O").
mega_example(1, ner, ",", "O").
mega_example(1, ner, "which", "O").
mega_example(1, ner, "may", "O").
mega_example(1, ner, "lead", "O").
mega_example(1, ner, "to", "O").
mega_example(1, ner, "adynamic", "O").
mega_example(1, ner, "bone", "O").
mega_example(1, ner, "disease", "O").
mega_example(1, ner, ".", "O").

mega_example(2, ner, "A", "O").
mega_example(2, ner, "new", "O").
mega_example(2, ner, "vitamin", "B").
mega_example(2, ner, "D", "I").
mega_example(2, ner, "analogue", "O").
mega_example(2, ner, ",", "O").
mega_example(2, ner, "22", "B").
mega_example(2, ner, "-", "I").
mega_example(2, ner, "oxacalcitriol", "I").
mega_example(2, ner, "(", "O").
mega_example(2, ner, "OCT", "B").
mega_example(2, ner, ")", "O").
mega_example(2, ner, ",", "O").
mega_example(2, ner, "has", "O").
mega_example(2, ner, "been", "O").
mega_example(2, ner, "shown", "O").
mega_example(2, ner, "to", "O").
mega_example(2, ner, "have", "O").
mega_example(2, ner, "promising", "O").
mega_example(2, ner, "characteristics", "O").
mega_example(2, ner, ".", "O").